

import type { Product, SaleTransaction, Client, Tax, AppliedTaxEntry, User, Promotion, Theme, ThemeColors, PaymentMethod, AppliedPayment, ReceiptSetting, CartItem, ReceiptMargin, PromotionCondition, Country, Currency, Supplier } from '@/types';

export const mockProducts: Omit<Product, 'id'>[] = [
  {
    name: 'Eco-Friendly Water Bottle',
    price: 15.99,
    quantity: 150,
    category: 'Drinkware',
    barcode: '1000000001',
    imageUrl: 'https://placehold.co/300x300.png',
    description: 'Reusable water bottle made from recycled materials.',
    sku: 'SKU-WB-ECO-001',
    measurementUnit: 'piece',
    cost: 8.00,
    markup: 100, 
    tax: 0.05, 
    isTaxInclusivePrice: false,
    isPriceChangeAllowed: true,
    isUsingDefaultQuantity: true,
    isService: false,
    isEnabled: true,
    supplier: 'Green Supplies Co.',
    reorderPoint: 20,
    preferredQuantity: 50,
    lowStockWarning: true,
    warningQuantity: 25
  },
  {
    name: 'Organic Cotton Tote Bag',
    price: 12.50,
    quantity: 200,
    category: 'Accessories',
    barcode: '1000000002',
    imageUrl: 'https://placehold.co/300x300.png',
    description: 'Durable and stylish tote bag for everyday use.',
    sku: 'SKU-TB-ORG-002',
    measurementUnit: 'piece',
    cost: 5.50,
    markup: 127.27,
    tax: 0.05,
    isTaxInclusivePrice: false,
    isPriceChangeAllowed: true,
    isUsingDefaultQuantity: true,
    isService: false,
    isEnabled: true,
    supplier: 'Eco Textiles Inc.',
    reorderPoint: 30,
    preferredQuantity: 60,
    lowStockWarning: true,
    warningQuantity: 40
  },
  {
    name: 'Bamboo Toothbrush Set (4-pack)',
    price: 8.99,
    quantity: 300,
    category: 'Personal Care',
    barcode: '1000000003',
    imageUrl: 'https://placehold.co/300x300.png',
    description: 'Biodegradable toothbrushes with charcoal bristles.',
    sku: 'SKU-TB-BAM-003',
    measurementUnit: 'pack',
    cost: 3.00,
    markup: 199.67,
    isTaxInclusivePrice: false,
    isPriceChangeAllowed: false,
    isUsingDefaultQuantity: true,
    isService: false,
    isEnabled: true,
    supplier: 'Natural Dental Care',
    reorderPoint: 50,
    preferredQuantity: 100,
    lowStockWarning: false,
    warningQuantity: 0
  },
  {
    name: 'Solar Powered Charger',
    price: 29.99,
    quantity: 80,
    category: 'Electronics',
    barcode: '1000000004',
    imageUrl: 'https://placehold.co/300x300.png',
    description: 'Portable solar charger for your devices.',
    sku: 'SKU-CHG-SOL-004',
    measurementUnit: 'piece',
    cost: 15.00,
    markup: 100,
    tax: 0.10,
    isTaxInclusivePrice: true,
    isPriceChangeAllowed: true,
    isUsingDefaultQuantity: true,
    isService: false,
    isEnabled: true,
    supplier: 'SunPower Tech',
    reorderPoint: 10,
    preferredQuantity: 25,
    lowStockWarning: true,
    warningQuantity: 15
  },
  {
    name: 'Artisan Coffee Beans (250g)',
    price: 10.00,
    quantity: 120,
    category: 'Groceries',
    barcode: '1000000005',
    imageUrl: 'https://placehold.co/300x300.png',
    description: 'Fair-trade, single-origin coffee beans.',
    sku: 'SKU-COF-ART-005',
    measurementUnit: 'bag',
    cost: 4.50,
    markup: 122.22,
    tax: 0, 
    isTaxInclusivePrice: false,
    isPriceChangeAllowed: true,
    isUsingDefaultQuantity: true,
    isService: false,
    isEnabled: true,
    supplier: 'The Coffee Roasters',
    reorderPoint: 20,
    preferredQuantity: 40,
    lowStockWarning: true,
    warningQuantity: 25
  },
  {
    name: "Hourly Design Service",
    sku: "SERV-DESIGN-HOUR",
    barcode: "SERV001",
    measurementUnit: "hour",
    cost: 20,
    markup: 150, 
    price: 50,
    tax: 0, 
    isTaxInclusivePrice: false,
    isPriceChangeAllowed: true,
    isUsingDefaultQuantity: false, 
    isService: true,
    isEnabled: true,
    description: "Professional design consultation and work, billed per hour.",
    quantity: 9999, 
    category: "Services",
  }
];

export const mockClients: Omit<Client, 'id'>[] = [
  { name: 'Alice Wonderland', email: 'alice@example.com', phone: '555-1234', address: '123 Main St, Anytown, USA', registrationDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString() },
  { name: 'Bob The Builder', email: 'bob@example.com', phone: '555-5678', address: '456 Oak Ave, Anytown, USA', registrationDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString() },
  { name: 'Charlie Brown', email: 'charlie@example.com', registrationDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString() },
  { name: 'Diana Prince', email: 'diana@example.com', phone: '555-9012', address: '789 Pine Ln, Anytown, USA', registrationDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString() },
];

export const mockTaxes: Omit<Tax, 'id'>[] = [
  { name: 'Standard Sales Tax', rate: 0.10, description: 'General sales tax applicable to most goods.' },
  { name: 'Reduced Rate Tax', rate: 0.05, description: 'Reduced tax rate for specific items.' },
  { name: 'Luxury Goods Tax', rate: 0.20, description: 'Additional tax for luxury items.' },
  { name: 'Eco Tax', rate: 0.02, description: 'Environmental tax on certain products.' },
];

export const mockUsers: Omit<User, 'id' | 'permissions'>[] = [
  { name: 'Admin User', email: 'admin@example.com', role: 'Admin', joinDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(), imageUrl: 'https://placehold.co/128x128.png?text=AU', status: 'active' },
  { name: 'Editor Dave', email: 'dave@example.com', role: 'Editor', joinDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(), imageUrl: 'https://placehold.co/128x128.png?text=ED', status: 'pending' },
  { name: 'Eve Viewer', email: 'eve@example.com', role: 'Viewer', joinDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), imageUrl: 'https://placehold.co/128x128.png?text=VE', status: 'pending' },
];

export const mockPaymentMethods: Omit<PaymentMethod, 'id'>[] = [
  { 
    name: { en: 'Cash', es: 'Efectivo' }, 
    description: { en: 'Physical currency.', es: 'Moneda física.' }, 
    isEnabled: true, 
    isDefault: true 
  },
  { 
    name: { en: 'Credit Card', es: 'Tarjeta de Crédito' }, 
    description: { en: 'Visa, Mastercard, Amex, etc.', es: 'Visa, Mastercard, Amex, etc.' }, 
    isEnabled: true 
  },
  { 
    name: { en: 'Debit Card', es: 'Tarjeta de Débito' }, 
    description: { en: 'Direct bank debit.', es: 'Débito directo bancario.' }, 
    isEnabled: true 
  },
  { 
    name: { en: 'Coupon', es: 'Cupón' }, 
    description: { en: 'Promotional or gift coupons.', es: 'Cupones promocionales o de regalo.' }, 
    isEnabled: true 
  },
  { 
    name: { en: 'Bank Transfer', es: 'Transferencia Bancaria' }, 
    description: { en: 'Direct bank transfer.', es: 'Transferencia bancaria directa.' }, 
    isEnabled: true 
  },
];

export const mockCountries: Omit<Country, 'id'>[] = [
  { name: 'Afghanistan', codeAlpha2: 'AF', codeAlpha3: 'AFG', numericCode: '004', currencyCode: 'AFN', flagImageUrl: 'https://flagcdn.com/w40/af.png', isEnabled: true, isDefault: false },
  { name: 'Albania', codeAlpha2: 'AL', codeAlpha3: 'ALB', numericCode: '008', currencyCode: 'ALL', flagImageUrl: 'https://flagcdn.com/w40/al.png', isEnabled: true, isDefault: false },
  { name: 'Algeria', codeAlpha2: 'DZ', codeAlpha3: 'DZA', numericCode: '012', currencyCode: 'DZD', flagImageUrl: 'https://flagcdn.com/w40/dz.png', isEnabled: true, isDefault: false },
  { name: 'American Samoa', codeAlpha2: 'AS', codeAlpha3: 'ASM', numericCode: '016', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/as.png', isEnabled: true, isDefault: false },
  { name: 'Andorra', codeAlpha2: 'AD', codeAlpha3: 'AND', numericCode: '020', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/ad.png', isEnabled: true, isDefault: false },
  { name: 'Angola', codeAlpha2: 'AO', codeAlpha3: 'AGO', numericCode: '024', currencyCode: 'AOA', flagImageUrl: 'https://flagcdn.com/w40/ao.png', isEnabled: true, isDefault: false },
  { name: 'Anguilla', codeAlpha2: 'AI', codeAlpha3: 'AIA', numericCode: '660', currencyCode: 'XCD', flagImageUrl: 'https://flagcdn.com/w40/ai.png', isEnabled: true, isDefault: false },
  { name: 'Antarctica', codeAlpha2: 'AQ', codeAlpha3: 'ATA', numericCode: '010', currencyCode: '', flagImageUrl: 'https://flagcdn.com/w40/aq.png', isEnabled: true, isDefault: false },
  { name: 'Antigua and Barbuda', codeAlpha2: 'AG', codeAlpha3: 'ATG', numericCode: '028', currencyCode: 'XCD', flagImageUrl: 'https://flagcdn.com/w40/ag.png', isEnabled: true, isDefault: false },
  { name: 'Argentina', codeAlpha2: 'AR', codeAlpha3: 'ARG', numericCode: '032', currencyCode: 'ARS', flagImageUrl: 'https://flagcdn.com/w40/ar.png', isEnabled: true, isDefault: false },
  { name: 'Armenia', codeAlpha2: 'AM', codeAlpha3: 'ARM', numericCode: '051', currencyCode: 'AMD', flagImageUrl: 'https://flagcdn.com/w40/am.png', isEnabled: true, isDefault: false },
  { name: 'Aruba', codeAlpha2: 'AW', codeAlpha3: 'ABW', numericCode: '533', currencyCode: 'AWG', flagImageUrl: 'https://flagcdn.com/w40/aw.png', isEnabled: true, isDefault: false },
  { name: 'Australia', codeAlpha2: 'AU', codeAlpha3: 'AUS', numericCode: '036', currencyCode: 'AUD', flagImageUrl: 'https://flagcdn.com/w40/au.png', isEnabled: true, isDefault: false },
  { name: 'Austria', codeAlpha2: 'AT', codeAlpha3: 'AUT', numericCode: '040', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/at.png', isEnabled: true, isDefault: false },
  { name: 'Azerbaijan', codeAlpha2: 'AZ', codeAlpha3: 'AZE', numericCode: '031', currencyCode: 'AZN', flagImageUrl: 'https://flagcdn.com/w40/az.png', isEnabled: true, isDefault: false },
  { name: 'Bahamas', codeAlpha2: 'BS', codeAlpha3: 'BHS', numericCode: '044', currencyCode: 'BSD', flagImageUrl: 'https://flagcdn.com/w40/bs.png', isEnabled: true, isDefault: false },
  { name: 'Bahrain', codeAlpha2: 'BH', codeAlpha3: 'BHR', numericCode: '048', currencyCode: 'BHD', flagImageUrl: 'https://flagcdn.com/w40/bh.png', isEnabled: true, isDefault: false },
  { name: 'Bangladesh', codeAlpha2: 'BD', codeAlpha3: 'BGD', numericCode: '050', currencyCode: 'BDT', flagImageUrl: 'https://flagcdn.com/w40/bd.png', isEnabled: true, isDefault: false },
  { name: 'Barbados', codeAlpha2: 'BB', codeAlpha3: 'BRB', numericCode: '052', currencyCode: 'BBD', flagImageUrl: 'https://flagcdn.com/w40/bb.png', isEnabled: true, isDefault: false },
  { name: 'Belarus', codeAlpha2: 'BY', codeAlpha3: 'BLR', numericCode: '112', currencyCode: 'BYN', flagImageUrl: 'https://flagcdn.com/w40/by.png', isEnabled: true, isDefault: false },
  { name: 'Belgium', codeAlpha2: 'BE', codeAlpha3: 'BEL', numericCode: '056', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/be.png', isEnabled: true, isDefault: false },
  { name: 'Belize', codeAlpha2: 'BZ', codeAlpha3: 'BLZ', numericCode: '084', currencyCode: 'BZD', flagImageUrl: 'https://flagcdn.com/w40/bz.png', isEnabled: true, isDefault: false },
  { name: 'Benin', codeAlpha2: 'BJ', codeAlpha3: 'BEN', numericCode: '204', currencyCode: 'XOF', flagImageUrl: 'https://flagcdn.com/w40/bj.png', isEnabled: true, isDefault: false },
  { name: 'Bermuda', codeAlpha2: 'BM', codeAlpha3: 'BMU', numericCode: '060', currencyCode: 'BMD', flagImageUrl: 'https://flagcdn.com/w40/bm.png', isEnabled: true, isDefault: false },
  { name: 'Bhutan', codeAlpha2: 'BT', codeAlpha3: 'BTN', numericCode: '064', currencyCode: 'BTN', flagImageUrl: 'https://flagcdn.com/w40/bt.png', isEnabled: true, isDefault: false },
  { name: 'Bolivia', codeAlpha2: 'BO', codeAlpha3: 'BOL', numericCode: '068', currencyCode: 'BOB', flagImageUrl: 'https://flagcdn.com/w40/bo.png', isEnabled: true, isDefault: false },
  { name: 'Bosnia and Herzegovina', codeAlpha2: 'BA', codeAlpha3: 'BIH', numericCode: '070', currencyCode: 'BAM', flagImageUrl: 'https://flagcdn.com/w40/ba.png', isEnabled: true, isDefault: false },
  { name: 'Botswana', codeAlpha2: 'BW', codeAlpha3: 'BWA', numericCode: '072', currencyCode: 'BWP', flagImageUrl: 'https://flagcdn.com/w40/bw.png', isEnabled: true, isDefault: false },
  { name: 'Brazil', codeAlpha2: 'BR', codeAlpha3: 'BRA', numericCode: '076', currencyCode: 'BRL', flagImageUrl: 'https://flagcdn.com/w40/br.png', isEnabled: true, isDefault: false },
  { name: 'British Indian Ocean Territory', codeAlpha2: 'IO', codeAlpha3: 'IOT', numericCode: '086', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/io.png', isEnabled: true, isDefault: false },
  { name: 'Brunei Darussalam', codeAlpha2: 'BN', codeAlpha3: 'BRN', numericCode: '096', currencyCode: 'BND', flagImageUrl: 'https://flagcdn.com/w40/bn.png', isEnabled: true, isDefault: false },
  { name: 'Bulgaria', codeAlpha2: 'BG', codeAlpha3: 'BGR', numericCode: '100', currencyCode: 'BGN', flagImageUrl: 'https://flagcdn.com/w40/bg.png', isEnabled: true, isDefault: false },
  { name: 'Burkina Faso', codeAlpha2: 'BF', codeAlpha3: 'BFA', numericCode: '854', currencyCode: 'XOF', flagImageUrl: 'https://flagcdn.com/w40/bf.png', isEnabled: true, isDefault: false },
  { name: 'Burundi', codeAlpha2: 'BI', codeAlpha3: 'BDI', numericCode: '108', currencyCode: 'BIF', flagImageUrl: 'https://flagcdn.com/w40/bi.png', isEnabled: true, isDefault: false },
  { name: 'Cabo Verde', codeAlpha2: 'CV', codeAlpha3: 'CPV', numericCode: '132', currencyCode: 'CVE', flagImageUrl: 'https://flagcdn.com/w40/cv.png', isEnabled: true, isDefault: false },
  { name: 'Cambodia', codeAlpha2: 'KH', codeAlpha3: 'KHM', numericCode: '116', currencyCode: 'KHR', flagImageUrl: 'https://flagcdn.com/w40/kh.png', isEnabled: true, isDefault: false },
  { name: 'Cameroon', codeAlpha2: 'CM', codeAlpha3: 'CMR', numericCode: '120', currencyCode: 'XAF', flagImageUrl: 'https://flagcdn.com/w40/cm.png', isEnabled: true, isDefault: false },
  { name: 'Canada', codeAlpha2: 'CA', codeAlpha3: 'CAN', numericCode: '124', currencyCode: 'CAD', flagImageUrl: 'https://flagcdn.com/w40/ca.png', isEnabled: true, isDefault: false },
  { name: 'Cayman Islands', codeAlpha2: 'KY', codeAlpha3: 'CYM', numericCode: '136', currencyCode: 'KYD', flagImageUrl: 'https://flagcdn.com/w40/ky.png', isEnabled: true, isDefault: false },
  { name: 'Central African Republic', codeAlpha2: 'CF', codeAlpha3: 'CAF', numericCode: '140', currencyCode: 'XAF', flagImageUrl: 'https://flagcdn.com/w40/cf.png', isEnabled: true, isDefault: false },
  { name: 'Chad', codeAlpha2: 'TD', codeAlpha3: 'TCD', numericCode: '148', currencyCode: 'XAF', flagImageUrl: 'https://flagcdn.com/w40/td.png', isEnabled: true, isDefault: false },
  { name: 'Chile', codeAlpha2: 'CL', codeAlpha3: 'CHL', numericCode: '152', currencyCode: 'CLP', flagImageUrl: 'https://flagcdn.com/w40/cl.png', isEnabled: true, isDefault: false },
  { name: 'China', codeAlpha2: 'CN', codeAlpha3: 'CHN', numericCode: '156', currencyCode: 'CNY', flagImageUrl: 'https://flagcdn.com/w40/cn.png', isEnabled: true, isDefault: false },
  { name: 'Christmas Island', codeAlpha2: 'CX', codeAlpha3: 'CXR', numericCode: '162', currencyCode: 'AUD', flagImageUrl: 'https://flagcdn.com/w40/cx.png', isEnabled: true, isDefault: false },
  { name: 'Cocos (Keeling) Islands', codeAlpha2: 'CC', codeAlpha3: 'CCK', numericCode: '166', currencyCode: 'AUD', flagImageUrl: 'https://flagcdn.com/w40/cc.png', isEnabled: true, isDefault: false },
  { name: 'Colombia', codeAlpha2: 'CO', codeAlpha3: 'COL', numericCode: '170', currencyCode: 'COP', flagImageUrl: 'https://flagcdn.com/w40/co.png', isEnabled: true, isDefault: false },
  { name: 'Comoros', codeAlpha2: 'KM', codeAlpha3: 'COM', numericCode: '174', currencyCode: 'KMF', flagImageUrl: 'https://flagcdn.com/w40/km.png', isEnabled: true, isDefault: false },
  { name: 'Congo', codeAlpha2: 'CG', codeAlpha3: 'COG', numericCode: '178', currencyCode: 'XAF', flagImageUrl: 'https://flagcdn.com/w40/cg.png', isEnabled: true, isDefault: false },
  { name: 'Congo (DRC)', codeAlpha2: 'CD', codeAlpha3: 'COD', numericCode: '180', currencyCode: 'CDF', flagImageUrl: 'https://flagcdn.com/w40/cd.png', isEnabled: true, isDefault: false },
  { name: 'Cook Islands', codeAlpha2: 'CK', codeAlpha3: 'COK', numericCode: '184', currencyCode: 'NZD', flagImageUrl: 'https://flagcdn.com/w40/ck.png', isEnabled: true, isDefault: false },
  { name: 'Costa Rica', codeAlpha2: 'CR', codeAlpha3: 'CRI', numericCode: '188', currencyCode: 'CRC', flagImageUrl: 'https://flagcdn.com/w40/cr.png', isEnabled: true, isDefault: false },
  { name: 'Croatia', codeAlpha2: 'HR', codeAlpha3: 'HRV', numericCode: '191', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/hr.png', isEnabled: true, isDefault: false },
  { name: 'Cuba', codeAlpha2: 'CU', codeAlpha3: 'CUB', numericCode: '192', currencyCode: 'CUP', flagImageUrl: 'https://flagcdn.com/w40/cu.png', isEnabled: true, isDefault: false },
  { name: 'Curaçao', codeAlpha2: 'CW', codeAlpha3: 'CUW', numericCode: '531', currencyCode: 'ANG', flagImageUrl: 'https://flagcdn.com/w40/cw.png', isEnabled: true, isDefault: false },
  { name: 'Cyprus', codeAlpha2: 'CY', codeAlpha3: 'CYP', numericCode: '196', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/cy.png', isEnabled: true, isDefault: false },
  { name: 'Czech Republic', codeAlpha2: 'CZ', codeAlpha3: 'CZE', numericCode: '203', currencyCode: 'CZK', flagImageUrl: 'https://flagcdn.com/w40/cz.png', isEnabled: true, isDefault: false },
  { name: 'Denmark', codeAlpha2: 'DK', codeAlpha3: 'DNK', numericCode: '208', currencyCode: 'DKK', flagImageUrl: 'https://flagcdn.com/w40/dk.png', isEnabled: true, isDefault: false },
  { name: 'Djibouti', codeAlpha2: 'DJ', codeAlpha3: 'DJI', numericCode: '262', currencyCode: 'DJF', flagImageUrl: 'https://flagcdn.com/w40/dj.png', isEnabled: true, isDefault: false },
  { name: 'Dominica', codeAlpha2: 'DM', codeAlpha3: 'DMA', numericCode: '212', currencyCode: 'XCD', flagImageUrl: 'https://flagcdn.com/w40/dm.png', isEnabled: true, isDefault: false },
  { name: 'Dominican Republic', codeAlpha2: 'DO', codeAlpha3: 'DOM', numericCode: '214', currencyCode: 'DOP', flagImageUrl: 'https://flagcdn.com/w40/do.png', isEnabled: true, isDefault: false },
  { name: 'Ecuador', codeAlpha2: 'EC', codeAlpha3: 'ECU', numericCode: '218', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/ec.png', isEnabled: true, isDefault: false },
  { name: 'Egypt', codeAlpha2: 'EG', codeAlpha3: 'EGY', numericCode: '818', currencyCode: 'EGP', flagImageUrl: 'https://flagcdn.com/w40/eg.png', isEnabled: true, isDefault: false },
  { name: 'El Salvador', codeAlpha2: 'SV', codeAlpha3: 'SLV', numericCode: '222', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/sv.png', isEnabled: true, isDefault: false },
  { name: 'Equatorial Guinea', codeAlpha2: 'GQ', codeAlpha3: 'GNQ', numericCode: '226', currencyCode: 'XAF', flagImageUrl: 'https://flagcdn.com/w40/gq.png', isEnabled: true, isDefault: false },
  { name: 'Eritrea', codeAlpha2: 'ER', codeAlpha3: 'ERI', numericCode: '232', currencyCode: 'ERN', flagImageUrl: 'https://flagcdn.com/w40/er.png', isEnabled: true, isDefault: false },
  { name: 'Estonia', codeAlpha2: 'EE', codeAlpha3: 'EST', numericCode: '233', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/ee.png', isEnabled: true, isDefault: false },
  { name: 'Eswatini', codeAlpha2: 'SZ', codeAlpha3: 'SWZ', numericCode: '748', currencyCode: 'SZL', flagImageUrl: 'https://flagcdn.com/w40/sz.png', isEnabled: true, isDefault: false },
  { name: 'Ethiopia', codeAlpha2: 'ET', codeAlpha3: 'ETH', numericCode: '231', currencyCode: 'ETB', flagImageUrl: 'https://flagcdn.com/w40/et.png', isEnabled: true, isDefault: false },
  { name: 'Falkland Islands', codeAlpha2: 'FK', codeAlpha3: 'FLK', numericCode: '238', currencyCode: 'FKP', flagImageUrl: 'https://flagcdn.com/w40/fk.png', isEnabled: true, isDefault: false },
  { name: 'Faroe Islands', codeAlpha2: 'FO', codeAlpha3: 'FRO', numericCode: '234', currencyCode: 'DKK', flagImageUrl: 'https://flagcdn.com/w40/fo.png', isEnabled: true, isDefault: false },
  { name: 'Fiji', codeAlpha2: 'FJ', codeAlpha3: 'FJI', numericCode: '242', currencyCode: 'FJD', flagImageUrl: 'https://flagcdn.com/w40/fj.png', isEnabled: true, isDefault: false },
  { name: 'Finland', codeAlpha2: 'FI', codeAlpha3: 'FIN', numericCode: '246', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/fi.png', isEnabled: true, isDefault: false },
  { name: 'France', codeAlpha2: 'FR', codeAlpha3: 'FRA', numericCode: '250', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/fr.png', isEnabled: true, isDefault: false },
  { name: 'French Guiana', codeAlpha2: 'GF', codeAlpha3: 'GUF', numericCode: '254', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/gf.png', isEnabled: true, isDefault: false },
  { name: 'French Polynesia', codeAlpha2: 'PF', codeAlpha3: 'PYF', numericCode: '258', currencyCode: 'XPF', flagImageUrl: 'https://flagcdn.com/w40/pf.png', isEnabled: true, isDefault: false },
  { name: 'Gabon', codeAlpha2: 'GA', codeAlpha3: 'GAB', numericCode: '266', currencyCode: 'XAF', flagImageUrl: 'https://flagcdn.com/w40/ga.png', isEnabled: true, isDefault: false },
  { name: 'Gambia', codeAlpha2: 'GM', codeAlpha3: 'GMB', numericCode: '270', currencyCode: 'GMD', flagImageUrl: 'https://flagcdn.com/w40/gm.png', isEnabled: true, isDefault: false },
  { name: 'Georgia', codeAlpha2: 'GE', codeAlpha3: 'GEO', numericCode: '268', currencyCode: 'GEL', flagImageUrl: 'https://flagcdn.com/w40/ge.png', isEnabled: true, isDefault: false },
  { name: 'Germany', codeAlpha2: 'DE', codeAlpha3: 'DEU', numericCode: '276', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/de.png', isEnabled: true, isDefault: false },
  { name: 'Ghana', codeAlpha2: 'GH', codeAlpha3: 'GHA', numericCode: '288', currencyCode: 'GHS', flagImageUrl: 'https://flagcdn.com/w40/gh.png', isEnabled: true, isDefault: false },
  { name: 'Gibraltar', codeAlpha2: 'GI', codeAlpha3: 'GIB', numericCode: '292', currencyCode: 'GIP', flagImageUrl: 'https://flagcdn.com/w40/gi.png', isEnabled: true, isDefault: false },
  { name: 'Greece', codeAlpha2: 'GR', codeAlpha3: 'GRC', numericCode: '300', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/gr.png', isEnabled: true, isDefault: false },
  { name: 'Greenland', codeAlpha2: 'GL', codeAlpha3: 'GRL', numericCode: '304', currencyCode: 'DKK', flagImageUrl: 'https://flagcdn.com/w40/gl.png', isEnabled: true, isDefault: false },
  { name: 'Grenada', codeAlpha2: 'GD', codeAlpha3: 'GRD', numericCode: '308', currencyCode: 'XCD', flagImageUrl: 'https://flagcdn.com/w40/gd.png', isEnabled: true, isDefault: false },
  { name: 'Guadeloupe', codeAlpha2: 'GP', codeAlpha3: 'GLP', numericCode: '312', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/gp.png', isEnabled: true, isDefault: false },
  { name: 'Guam', codeAlpha2: 'GU', codeAlpha3: 'GUM', numericCode: '316', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/gu.png', isEnabled: true, isDefault: false },
  { name: 'Guatemala', codeAlpha2: 'GT', codeAlpha3: 'GTM', numericCode: '320', currencyCode: 'GTQ', flagImageUrl: 'https://flagcdn.com/w40/gt.png', isEnabled: true, isDefault: false },
  { name: 'Guernsey', codeAlpha2: 'GG', codeAlpha3: 'GGY', numericCode: '831', currencyCode: 'GBP', flagImageUrl: 'https://flagcdn.com/w40/gg.png', isEnabled: true, isDefault: false },
  { name: 'Guinea', codeAlpha2: 'GN', codeAlpha3: 'GIN', numericCode: '324', currencyCode: 'GNF', flagImageUrl: 'https://flagcdn.com/w40/gn.png', isEnabled: true, isDefault: false },
  { name: 'Guinea-Bissau', codeAlpha2: 'GW', codeAlpha3: 'GNB', numericCode: '624', currencyCode: 'XOF', flagImageUrl: 'https://flagcdn.com/w40/gw.png', isEnabled: true, isDefault: false },
  { name: 'Guyana', codeAlpha2: 'GY', codeAlpha3: 'GUY', numericCode: '328', currencyCode: 'GYD', flagImageUrl: 'https://flagcdn.com/w40/gy.png', isEnabled: true, isDefault: false },
  { name: 'Haiti', codeAlpha2: 'HT', codeAlpha3: 'HTI', numericCode: '332', currencyCode: 'HTG', flagImageUrl: 'https://flagcdn.com/w40/ht.png', isEnabled: true, isDefault: false },
  { name: 'Honduras', codeAlpha2: 'HN', codeAlpha3: 'HND', numericCode: '340', currencyCode: 'HNL', flagImageUrl: 'https://flagcdn.com/w40/hn.png', isEnabled: true, isDefault: false },
  { name: 'Hong Kong', codeAlpha2: 'HK', codeAlpha3: 'HKG', numericCode: '344', currencyCode: 'HKD', flagImageUrl: 'https://flagcdn.com/w40/hk.png', isEnabled: true, isDefault: false },
  { name: 'Hungary', codeAlpha2: 'HU', codeAlpha3: 'HUN', numericCode: '348', currencyCode: 'HUF', flagImageUrl: 'https://flagcdn.com/w40/hu.png', isEnabled: true, isDefault: false },
  { name: 'Iceland', codeAlpha2: 'IS', codeAlpha3: 'ISL', numericCode: '352', currencyCode: 'ISK', flagImageUrl: 'https://flagcdn.com/w40/is.png', isEnabled: true, isDefault: false },
  { name: 'India', codeAlpha2: 'IN', codeAlpha3: 'IND', numericCode: '356', currencyCode: 'INR', flagImageUrl: 'https://flagcdn.com/w40/in.png', isEnabled: true, isDefault: false },
  { name: 'Indonesia', codeAlpha2: 'ID', codeAlpha3: 'IDN', numericCode: '360', currencyCode: 'IDR', flagImageUrl: 'https://flagcdn.com/w40/id.png', isEnabled: true, isDefault: false },
  { name: 'Iran', codeAlpha2: 'IR', codeAlpha3: 'IRN', numericCode: '364', currencyCode: 'IRR', flagImageUrl: 'https://flagcdn.com/w40/ir.png', isEnabled: true, isDefault: false },
  { name: 'Iraq', codeAlpha2: 'IQ', codeAlpha3: 'IRQ', numericCode: '368', currencyCode: 'IQD', flagImageUrl: 'https://flagcdn.com/w40/iq.png', isEnabled: true, isDefault: false },
  { name: 'Ireland', codeAlpha2: 'IE', codeAlpha3: 'IRL', numericCode: '372', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/ie.png', isEnabled: true, isDefault: false },
  { name: 'Isle of Man', codeAlpha2: 'IM', codeAlpha3: 'IMN', numericCode: '833', currencyCode: 'GBP', flagImageUrl: 'https://flagcdn.com/w40/im.png', isEnabled: true, isDefault: false },
  { name: 'Israel', codeAlpha2: 'IL', codeAlpha3: 'ISR', numericCode: '376', currencyCode: 'ILS', flagImageUrl: 'https://flagcdn.com/w40/il.png', isEnabled: true, isDefault: false },
  { name: 'Italy', codeAlpha2: 'IT', codeAlpha3: 'ITA', numericCode: '380', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/it.png', isEnabled: true, isDefault: false },
  { name: 'Jamaica', codeAlpha2: 'JM', codeAlpha3: 'JAM', numericCode: '388', currencyCode: 'JMD', flagImageUrl: 'https://flagcdn.com/w40/jm.png', isEnabled: true, isDefault: false },
  { name: 'Japan', codeAlpha2: 'JP', codeAlpha3: 'JPN', numericCode: '392', currencyCode: 'JPY', flagImageUrl: 'https://flagcdn.com/w40/jp.png', isEnabled: true, isDefault: false },
  { name: 'Jersey', codeAlpha2: 'JE', codeAlpha3: 'JEY', numericCode: '832', currencyCode: 'GBP', flagImageUrl: 'https://flagcdn.com/w40/je.png', isEnabled: true, isDefault: false },
  { name: 'Jordan', codeAlpha2: 'JO', codeAlpha3: 'JOR', numericCode: '400', currencyCode: 'JOD', flagImageUrl: 'https://flagcdn.com/w40/jo.png', isEnabled: true, isDefault: false },
  { name: 'Kazakhstan', codeAlpha2: 'KZ', codeAlpha3: 'KAZ', numericCode: '398', currencyCode: 'KZT', flagImageUrl: 'https://flagcdn.com/w40/kz.png', isEnabled: true, isDefault: false },
  { name: 'Kenya', codeAlpha2: 'KE', codeAlpha3: 'KEN', numericCode: '404', currencyCode: 'KES', flagImageUrl: 'https://flagcdn.com/w40/ke.png', isEnabled: true, isDefault: false },
  { name: 'Kiribati', codeAlpha2: 'KI', codeAlpha3: 'KIR', numericCode: '296', currencyCode: 'AUD', flagImageUrl: 'https://flagcdn.com/w40/ki.png', isEnabled: true, isDefault: false },
  { name: 'Kuwait', codeAlpha2: 'KW', codeAlpha3: 'KWT', numericCode: '414', currencyCode: 'KWD', flagImageUrl: 'https://flagcdn.com/w40/kw.png', isEnabled: true, isDefault: false },
  { name: 'Kyrgyzstan', codeAlpha2: 'KG', codeAlpha3: 'KGZ', numericCode: '417', currencyCode: 'KGS', flagImageUrl: 'https://flagcdn.com/w40/kg.png', isEnabled: true, isDefault: false },
  { name: 'Laos', codeAlpha2: 'LA', codeAlpha3: 'LAO', numericCode: '418', currencyCode: 'LAK', flagImageUrl: 'https://flagcdn.com/w40/la.png', isEnabled: true, isDefault: false },
  { name: 'Latvia', codeAlpha2: 'LV', codeAlpha3: 'LVA', numericCode: '428', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/lv.png', isEnabled: true, isDefault: false },
  { name: 'Lebanon', codeAlpha2: 'LB', codeAlpha3: 'LBN', numericCode: '422', currencyCode: 'LBP', flagImageUrl: 'https://flagcdn.com/w40/lb.png', isEnabled: true, isDefault: false },
  { name: 'Lesotho', codeAlpha2: 'LS', codeAlpha3: 'LSO', numericCode: '426', currencyCode: 'LSL', flagImageUrl: 'https://flagcdn.com/w40/ls.png', isEnabled: true, isDefault: false },
  { name: 'Liberia', codeAlpha2: 'LR', codeAlpha3: 'LBR', numericCode: '430', currencyCode: 'LRD', flagImageUrl: 'https://flagcdn.com/w40/lr.png', isEnabled: true, isDefault: false },
  { name: 'Libya', codeAlpha2: 'LY', codeAlpha3: 'LBY', numericCode: '434', currencyCode: 'LYD', flagImageUrl: 'https://flagcdn.com/w40/ly.png', isEnabled: true, isDefault: false },
  { name: 'Liechtenstein', codeAlpha2: 'LI', codeAlpha3: 'LIE', numericCode: '438', currencyCode: 'CHF', flagImageUrl: 'https://flagcdn.com/w40/li.png', isEnabled: true, isDefault: false },
  { name: 'Lithuania', codeAlpha2: 'LT', codeAlpha3: 'LTU', numericCode: '440', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/lt.png', isEnabled: true, isDefault: false },
  { name: 'Luxembourg', codeAlpha2: 'LU', codeAlpha3: 'LUX', numericCode: '442', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/lu.png', isEnabled: true, isDefault: false },
  { name: 'Macao', codeAlpha2: 'MO', codeAlpha3: 'MAC', numericCode: '446', currencyCode: 'MOP', flagImageUrl: 'https://flagcdn.com/w40/mo.png', isEnabled: true, isDefault: false },
  { name: 'Madagascar', codeAlpha2: 'MG', codeAlpha3: 'MDG', numericCode: '450', currencyCode: 'MGA', flagImageUrl: 'https://flagcdn.com/w40/mg.png', isEnabled: true, isDefault: false },
  { name: 'Malawi', codeAlpha2: 'MW', codeAlpha3: 'MWI', numericCode: '454', currencyCode: 'MWK', flagImageUrl: 'https://flagcdn.com/w40/mw.png', isEnabled: true, isDefault: false },
  { name: 'Malaysia', codeAlpha2: 'MY', codeAlpha3: 'MYS', numericCode: '458', currencyCode: 'MYR', flagImageUrl: 'https://flagcdn.com/w40/my.png', isEnabled: true, isDefault: false },
  { name: 'Maldives', codeAlpha2: 'MV', codeAlpha3: 'MDV', numericCode: '462', currencyCode: 'MVR', flagImageUrl: 'https://flagcdn.com/w40/mv.png', isEnabled: true, isDefault: false },
  { name: 'Mali', codeAlpha2: 'ML', codeAlpha3: 'MLI', numericCode: '466', currencyCode: 'XOF', flagImageUrl: 'https://flagcdn.com/w40/ml.png', isEnabled: true, isDefault: false },
  { name: 'Malta', codeAlpha2: 'MT', codeAlpha3: 'MLT', numericCode: '470', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/mt.png', isEnabled: true, isDefault: false },
  { name: 'Marshall Islands', codeAlpha2: 'MH', codeAlpha3: 'MHL', numericCode: '584', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/mh.png', isEnabled: true, isDefault: false },
  { name: 'Martinique', codeAlpha2: 'MQ', codeAlpha3: 'MTQ', numericCode: '474', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/mq.png', isEnabled: true, isDefault: false },
  { name: 'Mauritania', codeAlpha2: 'MR', codeAlpha3: 'MRT', numericCode: '478', currencyCode: 'MRU', flagImageUrl: 'https://flagcdn.com/w40/mr.png', isEnabled: true, isDefault: false },
  { name: 'Mauritius', codeAlpha2: 'MU', codeAlpha3: 'MUS', numericCode: '480', currencyCode: 'MUR', flagImageUrl: 'https://flagcdn.com/w40/mu.png', isEnabled: true, isDefault: false },
  { name: 'Mayotte', codeAlpha2: 'YT', codeAlpha3: 'MYT', numericCode: '175', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/yt.png', isEnabled: true, isDefault: false },
  { name: 'Mexico', codeAlpha2: 'MX', codeAlpha3: 'MEX', numericCode: '484', currencyCode: 'MXN', flagImageUrl: 'https://flagcdn.com/w40/mx.png', isEnabled: true, isDefault: false },
  { name: 'Micronesia', codeAlpha2: 'FM', codeAlpha3: 'FSM', numericCode: '583', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/fm.png', isEnabled: true, isDefault: false },
  { name: 'Moldova', codeAlpha2: 'MD', codeAlpha3: 'MDA', numericCode: '498', currencyCode: 'MDL', flagImageUrl: 'https://flagcdn.com/w40/md.png', isEnabled: true, isDefault: false },
  { name: 'Monaco', codeAlpha2: 'MC', codeAlpha3: 'MCO', numericCode: '492', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/mc.png', isEnabled: true, isDefault: false },
  { name: 'Mongolia', codeAlpha2: 'MN', codeAlpha3: 'MNG', numericCode: '496', currencyCode: 'MNT', flagImageUrl: 'https://flagcdn.com/w40/mn.png', isEnabled: true, isDefault: false },
  { name: 'Montenegro', codeAlpha2: 'ME', codeAlpha3: 'MNE', numericCode: '499', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/me.png', isEnabled: true, isDefault: false },
  { name: 'Montserrat', codeAlpha2: 'MS', codeAlpha3: 'MSR', numericCode: '500', currencyCode: 'XCD', flagImageUrl: 'https://flagcdn.com/w40/ms.png', isEnabled: true, isDefault: false },
  { name: 'Morocco', codeAlpha2: 'MA', codeAlpha3: 'MAR', numericCode: '504', currencyCode: 'MAD', flagImageUrl: 'https://flagcdn.com/w40/ma.png', isEnabled: true, isDefault: false },
  { name: 'Mozambique', codeAlpha2: 'MZ', codeAlpha3: 'MOZ', numericCode: '508', currencyCode: 'MZN', flagImageUrl: 'https://flagcdn.com/w40/mz.png', isEnabled: true, isDefault: false },
  { name: 'Myanmar', codeAlpha2: 'MM', codeAlpha3: 'MMR', numericCode: '104', currencyCode: 'MMK', flagImageUrl: 'https://flagcdn.com/w40/mm.png', isEnabled: true, isDefault: false },
  { name: 'Namibia', codeAlpha2: 'NA', codeAlpha3: 'NAM', numericCode: '516', currencyCode: 'NAD', flagImageUrl: 'https://flagcdn.com/w40/na.png', isEnabled: true, isDefault: false },
  { name: 'Nauru', codeAlpha2: 'NR', codeAlpha3: 'NRU', numericCode: '520', currencyCode: 'AUD', flagImageUrl: 'https://flagcdn.com/w40/nr.png', isEnabled: true, isDefault: false },
  { name: 'Nepal', codeAlpha2: 'NP', codeAlpha3: 'NPL', numericCode: '524', currencyCode: 'NPR', flagImageUrl: 'https://flagcdn.com/w40/np.png', isEnabled: true, isDefault: false },
  { name: 'Netherlands', codeAlpha2: 'NL', codeAlpha3: 'NLD', numericCode: '528', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/nl.png', isEnabled: true, isDefault: false },
  { name: 'New Caledonia', codeAlpha2: 'NC', codeAlpha3: 'NCL', numericCode: '540', currencyCode: 'XPF', flagImageUrl: 'https://flagcdn.com/w40/nc.png', isEnabled: true, isDefault: false },
  { name: 'New Zealand', codeAlpha2: 'NZ', codeAlpha3: 'NZL', numericCode: '554', currencyCode: 'NZD', flagImageUrl: 'https://flagcdn.com/w40/nz.png', isEnabled: true, isDefault: false },
  { name: 'Nicaragua', codeAlpha2: 'NI', codeAlpha3: 'NIC', numericCode: '558', currencyCode: 'NIO', flagImageUrl: 'https://flagcdn.com/w40/ni.png', isEnabled: true, isDefault: false },
  { name: 'Niger', codeAlpha2: 'NE', codeAlpha3: 'NER', numericCode: '562', currencyCode: 'XOF', flagImageUrl: 'https://flagcdn.com/w40/ne.png', isEnabled: true, isDefault: false },
  { name: 'Nigeria', codeAlpha2: 'NG', codeAlpha3: 'NGA', numericCode: '566', currencyCode: 'NGN', flagImageUrl: 'https://flagcdn.com/w40/ng.png', isEnabled: true, isDefault: false },
  { name: 'Niue', codeAlpha2: 'NU', codeAlpha3: 'NIU', numericCode: '570', currencyCode: 'NZD', flagImageUrl: 'https://flagcdn.com/w40/nu.png', isEnabled: true, isDefault: false },
  { name: 'Norfolk Island', codeAlpha2: 'NF', codeAlpha3: 'NFK', numericCode: '574', currencyCode: 'AUD', flagImageUrl: 'https://flagcdn.com/w40/nf.png', isEnabled: true, isDefault: false },
  { name: 'North Korea', codeAlpha2: 'KP', codeAlpha3: 'PRK', numericCode: '408', currencyCode: 'KPW', flagImageUrl: 'https://flagcdn.com/w40/kp.png', isEnabled: true, isDefault: false },
  { name: 'North Macedonia', codeAlpha2: 'MK', codeAlpha3: 'MKD', numericCode: '807', currencyCode: 'MKD', flagImageUrl: 'https://flagcdn.com/w40/mk.png', isEnabled: true, isDefault: false },
  { name: 'Northern Mariana Islands', codeAlpha2: 'MP', codeAlpha3: 'MNP', numericCode: '580', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/mp.png', isEnabled: true, isDefault: false },
  { name: 'Norway', codeAlpha2: 'NO', codeAlpha3: 'NOR', numericCode: '578', currencyCode: 'NOK', flagImageUrl: 'https://flagcdn.com/w40/no.png', isEnabled: true, isDefault: false },
  { name: 'Oman', codeAlpha2: 'OM', codeAlpha3: 'OMN', numericCode: '512', currencyCode: 'OMR', flagImageUrl: 'https://flagcdn.com/w40/om.png', isEnabled: true, isDefault: false },
  { name: 'Pakistan', codeAlpha2: 'PK', codeAlpha3: 'PAK', numericCode: '586', currencyCode: 'PKR', flagImageUrl: 'https://flagcdn.com/w40/pk.png', isEnabled: true, isDefault: false },
  { name: 'Palau', codeAlpha2: 'PW', codeAlpha3: 'PLW', numericCode: '585', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/pw.png', isEnabled: true, isDefault: false },
  { name: 'Palestine', codeAlpha2: 'PS', codeAlpha3: 'PSE', numericCode: '275', currencyCode: 'ILS', flagImageUrl: 'https://flagcdn.com/w40/ps.png', isEnabled: true, isDefault: false },
  { name: 'Panama', codeAlpha2: 'PA', codeAlpha3: 'PAN', numericCode: '591', currencyCode: 'PAB', flagImageUrl: 'https://flagcdn.com/w40/pa.png', isEnabled: true, isDefault: false },
  { name: 'Papua New Guinea', codeAlpha2: 'PG', codeAlpha3: 'PNG', numericCode: '598', currencyCode: 'PGK', flagImageUrl: 'https://flagcdn.com/w40/pg.png', isEnabled: true, isDefault: false },
  { name: 'Paraguay', codeAlpha2: 'PY', codeAlpha3: 'PRY', numericCode: '600', currencyCode: 'PYG', flagImageUrl: 'https://flagcdn.com/w40/py.png', isEnabled: true, isDefault: false },
  { name: 'Peru', codeAlpha2: 'PE', codeAlpha3: 'PER', numericCode: '604', currencyCode: 'PEN', flagImageUrl: 'https://flagcdn.com/w40/pe.png', isEnabled: true, isDefault: false },
  { name: 'Philippines', codeAlpha2: 'PH', codeAlpha3: 'PHL', numericCode: '608', currencyCode: 'PHP', flagImageUrl: 'https://flagcdn.com/w40/ph.png', isEnabled: true, isDefault: false },
  { name: 'Poland', codeAlpha2: 'PL', codeAlpha3: 'POL', numericCode: '616', currencyCode: 'PLN', flagImageUrl: 'https://flagcdn.com/w40/pl.png', isEnabled: true, isDefault: false },
  { name: 'Portugal', codeAlpha2: 'PT', codeAlpha3: 'PRT', numericCode: '620', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/pt.png', isEnabled: true, isDefault: false },
  { name: 'Puerto Rico', codeAlpha2: 'PR', codeAlpha3: 'PRI', numericCode: '630', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/pr.png', isEnabled: true, isDefault: false },
  { name: 'Qatar', codeAlpha2: 'QA', codeAlpha3: 'QAT', numericCode: '634', currencyCode: 'QAR', flagImageUrl: 'https://flagcdn.com/w40/qa.png', isEnabled: true, isDefault: false },
  { name: 'Réunion', codeAlpha2: 'RE', codeAlpha3: 'REU', numericCode: '638', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/re.png', isEnabled: true, isDefault: false },
  { name: 'Romania', codeAlpha2: 'RO', codeAlpha3: 'ROU', numericCode: '642', currencyCode: 'RON', flagImageUrl: 'https://flagcdn.com/w40/ro.png', isEnabled: true, isDefault: false },
  { name: 'Russia', codeAlpha2: 'RU', codeAlpha3: 'RUS', numericCode: '643', currencyCode: 'RUB', flagImageUrl: 'https://flagcdn.com/w40/ru.png', isEnabled: true, isDefault: false },
  { name: 'Rwanda', codeAlpha2: 'RW', codeAlpha3: 'RWA', numericCode: '646', currencyCode: 'RWF', flagImageUrl: 'https://flagcdn.com/w40/rw.png', isEnabled: true, isDefault: false },
  { name: 'Saint Barthélemy', codeAlpha2: 'BL', codeAlpha3: 'BLM', numericCode: '652', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/bl.png', isEnabled: true, isDefault: false },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', codeAlpha2: 'SH', codeAlpha3: 'SHN', numericCode: '654', currencyCode: 'SHP', flagImageUrl: 'https://flagcdn.com/w40/sh.png', isEnabled: true, isDefault: false },
  { name: 'Saint Kitts and Nevis', codeAlpha2: 'KN', codeAlpha3: 'KNA', numericCode: '659', currencyCode: 'XCD', flagImageUrl: 'https://flagcdn.com/w40/kn.png', isEnabled: true, isDefault: false },
  { name: 'Saint Lucia', codeAlpha2: 'LC', codeAlpha3: 'LCA', numericCode: '662', currencyCode: 'XCD', flagImageUrl: 'https://flagcdn.com/w40/lc.png', isEnabled: true, isDefault: false },
  { name: 'Saint Martin (French part)', codeAlpha2: 'MF', codeAlpha3: 'MAF', numericCode: '663', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/mf.png', isEnabled: true, isDefault: false },
  { name: 'Saint Pierre and Miquelon', codeAlpha2: 'PM', codeAlpha3: 'SPM', numericCode: '666', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/pm.png', isEnabled: true, isDefault: false },
  { name: 'Saint Vincent and the Grenadines', codeAlpha2: 'VC', codeAlpha3: 'VCT', numericCode: '670', currencyCode: 'XCD', flagImageUrl: 'https://flagcdn.com/w40/vc.png', isEnabled: true, isDefault: false },
  { name: 'Samoa', codeAlpha2: 'WS', codeAlpha3: 'WSM', numericCode: '882', currencyCode: 'WST', flagImageUrl: 'https://flagcdn.com/w40/ws.png', isEnabled: true, isDefault: false },
  { name: 'San Marino', codeAlpha2: 'SM', codeAlpha3: 'SMR', numericCode: '674', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/sm.png', isEnabled: true, isDefault: false },
  { name: 'Sao Tome and Principe', codeAlpha2: 'ST', codeAlpha3: 'STP', numericCode: '678', currencyCode: 'STN', flagImageUrl: 'https://flagcdn.com/w40/st.png', isEnabled: true, isDefault: false },
  { name: 'Saudi Arabia', codeAlpha2: 'SA', codeAlpha3: 'SAU', numericCode: '682', currencyCode: 'SAR', flagImageUrl: 'https://flagcdn.com/w40/sa.png', isEnabled: true, isDefault: false },
  { name: 'Senegal', codeAlpha2: 'SN', codeAlpha3: 'SEN', numericCode: '686', currencyCode: 'XOF', flagImageUrl: 'https://flagcdn.com/w40/sn.png', isEnabled: true, isDefault: false },
  { name: 'Serbia', codeAlpha2: 'RS', codeAlpha3: 'SRB', numericCode: '688', currencyCode: 'RSD', flagImageUrl: 'https://flagcdn.com/w40/rs.png', isEnabled: true, isDefault: false },
  { name: 'Seychelles', codeAlpha2: 'SC', codeAlpha3: 'SYC', numericCode: '690', currencyCode: 'SCR', flagImageUrl: 'https://flagcdn.com/w40/sc.png', isEnabled: true, isDefault: false },
  { name: 'Sierra Leone', codeAlpha2: 'SL', codeAlpha3: 'SLE', numericCode: '694', currencyCode: 'SLL', flagImageUrl: 'https://flagcdn.com/w40/sl.png', isEnabled: true, isDefault: false },
  { name: 'Singapore', codeAlpha2: 'SG', codeAlpha3: 'SGP', numericCode: '702', currencyCode: 'SGD', flagImageUrl: 'https://flagcdn.com/w40/sg.png', isEnabled: true, isDefault: false },
  { name: 'Sint Maarten (Dutch part)', codeAlpha2: 'SX', codeAlpha3: 'SXM', numericCode: '534', currencyCode: 'ANG', flagImageUrl: 'https://flagcdn.com/w40/sx.png', isEnabled: true, isDefault: false },
  { name: 'Slovakia', codeAlpha2: 'SK', codeAlpha3: 'SVK', numericCode: '703', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/sk.png', isEnabled: true, isDefault: false },
  { name: 'Slovenia', codeAlpha2: 'SI', codeAlpha3: 'SVN', numericCode: '705', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/si.png', isEnabled: true, isDefault: false },
  { name: 'Solomon Islands', codeAlpha2: 'SB', codeAlpha3: 'SLB', numericCode: '090', currencyCode: 'SBD', flagImageUrl: 'https://flagcdn.com/w40/sb.png', isEnabled: true, isDefault: false },
  { name: 'Somalia', codeAlpha2: 'SO', codeAlpha3: 'SOM', numericCode: '706', currencyCode: 'SOS', flagImageUrl: 'https://flagcdn.com/w40/so.png', isEnabled: true, isDefault: false },
  { name: 'South Africa', codeAlpha2: 'ZA', codeAlpha3: 'ZAF', numericCode: '710', currencyCode: 'ZAR', flagImageUrl: 'https://flagcdn.com/w40/za.png', isEnabled: true, isDefault: false },
  { name: 'South Korea', codeAlpha2: 'KR', codeAlpha3: 'KOR', numericCode: '410', currencyCode: 'KRW', flagImageUrl: 'https://flagcdn.com/w40/kr.png', isEnabled: true, isDefault: false },
  { name: 'South Sudan', codeAlpha2: 'SS', codeAlpha3: 'SSD', numericCode: '728', currencyCode: 'SSP', flagImageUrl: 'https://flagcdn.com/w40/ss.png', isEnabled: true, isDefault: false },
  { name: 'Spain', codeAlpha2: 'ES', codeAlpha3: 'ESP', numericCode: '724', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/es.png', isEnabled: true, isDefault: true }, // Set Spain as default
  { name: 'Sri Lanka', codeAlpha2: 'LK', codeAlpha3: 'LKA', numericCode: '144', currencyCode: 'LKR', flagImageUrl: 'https://flagcdn.com/w40/lk.png', isEnabled: true, isDefault: false },
  { name: 'Sudan', codeAlpha2: 'SD', codeAlpha3: 'SDN', numericCode: '729', currencyCode: 'SDG', flagImageUrl: 'https://flagcdn.com/w40/sd.png', isEnabled: true, isDefault: false },
  { name: 'Suriname', codeAlpha2: 'SR', codeAlpha3: 'SUR', numericCode: '740', currencyCode: 'SRD', flagImageUrl: 'https://flagcdn.com/w40/sr.png', isEnabled: true, isDefault: false },
  { name: 'Sweden', codeAlpha2: 'SE', codeAlpha3: 'SWE', numericCode: '752', currencyCode: 'SEK', flagImageUrl: 'https://flagcdn.com/w40/se.png', isEnabled: true, isDefault: false },
  { name: 'Switzerland', codeAlpha2: 'CH', codeAlpha3: 'CHE', numericCode: '756', currencyCode: 'CHF', flagImageUrl: 'https://flagcdn.com/w40/ch.png', isEnabled: true, isDefault: false },
  { name: 'Syria', codeAlpha2: 'SY', codeAlpha3: 'SYR', numericCode: '760', currencyCode: 'SYP', flagImageUrl: 'https://flagcdn.com/w40/sy.png', isEnabled: true, isDefault: false },
  { name: 'Taiwan', codeAlpha2: 'TW', codeAlpha3: 'TWN', numericCode: '158', currencyCode: 'TWD', flagImageUrl: 'https://flagcdn.com/w40/tw.png', isEnabled: true, isDefault: false },
  { name: 'Tajikistan', codeAlpha2: 'TJ', codeAlpha3: 'TJK', numericCode: '762', currencyCode: 'TJS', flagImageUrl: 'https://flagcdn.com/w40/tj.png', isEnabled: true, isDefault: false },
  { name: 'Tanzania', codeAlpha2: 'TZ', codeAlpha3: 'TZA', numericCode: '834', currencyCode: 'TZS', flagImageUrl: 'https://flagcdn.com/w40/tz.png', isEnabled: true, isDefault: false },
  { name: 'Thailand', codeAlpha2: 'TH', codeAlpha3: 'THA', numericCode: '764', currencyCode: 'THB', flagImageUrl: 'https://flagcdn.com/w40/th.png', isEnabled: true, isDefault: false },
  { name: 'Timor-Leste', codeAlpha2: 'TL', codeAlpha3: 'TLS', numericCode: '626', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/tl.png', isEnabled: true, isDefault: false },
  { name: 'Togo', codeAlpha2: 'TG', codeAlpha3: 'TGO', numericCode: '768', currencyCode: 'XOF', flagImageUrl: 'https://flagcdn.com/w40/tg.png', isEnabled: true, isDefault: false },
  { name: 'Tokelau', codeAlpha2: 'TK', codeAlpha3: 'TKL', numericCode: '772', currencyCode: 'NZD', flagImageUrl: 'https://flagcdn.com/w40/tk.png', isEnabled: true, isDefault: false },
  { name: 'Tonga', codeAlpha2: 'TO', codeAlpha3: 'TON', numericCode: '776', currencyCode: 'TOP', flagImageUrl: 'https://flagcdn.com/w40/to.png', isEnabled: true, isDefault: false },
  { name: 'Trinidad and Tobago', codeAlpha2: 'TT', codeAlpha3: 'TTO', numericCode: '780', currencyCode: 'TTD', flagImageUrl: 'https://flagcdn.com/w40/tt.png', isEnabled: true, isDefault: false },
  { name: 'Tunisia', codeAlpha2: 'TN', codeAlpha3: 'TUN', numericCode: '788', currencyCode: 'TND', flagImageUrl: 'https://flagcdn.com/w40/tn.png', isEnabled: true, isDefault: false },
  { name: 'Turkey', codeAlpha2: 'TR', codeAlpha3: 'TUR', numericCode: '792', currencyCode: 'TRY', flagImageUrl: 'https://flagcdn.com/w40/tr.png', isEnabled: true, isDefault: false },
  { name: 'Turkmenistan', codeAlpha2: 'TM', codeAlpha3: 'TKM', numericCode: '795', currencyCode: 'TMT', flagImageUrl: 'https://flagcdn.com/w40/tm.png', isEnabled: true, isDefault: false },
  { name: 'Turks and Caicos Islands', codeAlpha2: 'TC', codeAlpha3: 'TCA', numericCode: '796', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/tc.png', isEnabled: true, isDefault: false },
  { name: 'Tuvalu', codeAlpha2: 'TV', codeAlpha3: 'TUV', numericCode: '798', currencyCode: 'AUD', flagImageUrl: 'https://flagcdn.com/w40/tv.png', isEnabled: true, isDefault: false },
  { name: 'Uganda', codeAlpha2: 'UG', codeAlpha3: 'UGA', numericCode: '800', currencyCode: 'UGX', flagImageUrl: 'https://flagcdn.com/w40/ug.png', isEnabled: true, isDefault: false },
  { name: 'Ukraine', codeAlpha2: 'UA', codeAlpha3: 'UKR', numericCode: '804', currencyCode: 'UAH', flagImageUrl: 'https://flagcdn.com/w40/ua.png', isEnabled: true, isDefault: false },
  { name: 'United Arab Emirates', codeAlpha2: 'AE', codeAlpha3: 'ARE', numericCode: '784', currencyCode: 'AED', flagImageUrl: 'https://flagcdn.com/w40/ae.png', isEnabled: true, isDefault: false },
  { name: 'United Kingdom', codeAlpha2: 'GB', codeAlpha3: 'GBR', numericCode: '826', currencyCode: 'GBP', flagImageUrl: 'https://flagcdn.com/w40/gb.png', isEnabled: true, isDefault: false },
  { name: 'United States', codeAlpha2: 'US', codeAlpha3: 'USA', numericCode: '840', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/us.png', isEnabled: true, isDefault: false }, // Previous default was US
  { name: 'Uruguay', codeAlpha2: 'UY', codeAlpha3: 'URY', numericCode: '858', currencyCode: 'UYU', flagImageUrl: 'https://flagcdn.com/w40/uy.png', isEnabled: true, isDefault: false },
  { name: 'Uzbekistan', codeAlpha2: 'UZ', codeAlpha3: 'UZB', numericCode: '860', currencyCode: 'UZS', flagImageUrl: 'https://flagcdn.com/w40/uz.png', isEnabled: true, isDefault: false },
  { name: 'Vanuatu', codeAlpha2: 'VU', codeAlpha3: 'VUT', numericCode: '548', currencyCode: 'VUV', flagImageUrl: 'https://flagcdn.com/w40/vu.png', isEnabled: true, isDefault: false },
  { name: 'Vatican City', codeAlpha2: 'VA', codeAlpha3: 'VAT', numericCode: '336', currencyCode: 'EUR', flagImageUrl: 'https://flagcdn.com/w40/va.png', isEnabled: true, isDefault: false },
  { name: 'Venezuela', codeAlpha2: 'VE', codeAlpha3: 'VEN', numericCode: '862', currencyCode: 'VES', flagImageUrl: 'https://flagcdn.com/w40/ve.png', isEnabled: true, isDefault: false },
  { name: 'Vietnam', codeAlpha2: 'VN', codeAlpha3: 'VNM', numericCode: '704', currencyCode: 'VND', flagImageUrl: 'https://flagcdn.com/w40/vn.png', isEnabled: true, isDefault: false },
  { name: 'Virgin Islands (British)', codeAlpha2: 'VG', codeAlpha3: 'VGB', numericCode: '092', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/vg.png', isEnabled: true, isDefault: false },
  { name: 'Virgin Islands (U.S.)', codeAlpha2: 'VI', codeAlpha3: 'VIR', numericCode: '850', currencyCode: 'USD', flagImageUrl: 'https://flagcdn.com/w40/vi.png', isEnabled: true, isDefault: false },
  { name: 'Wallis and Futuna', codeAlpha2: 'WF', codeAlpha3: 'WLF', numericCode: '876', currencyCode: 'XPF', flagImageUrl: 'https://flagcdn.com/w40/wf.png', isEnabled: true, isDefault: false },
  { name: 'Western Sahara', codeAlpha2: 'EH', codeAlpha3: 'ESH', numericCode: '732', currencyCode: 'MAD', flagImageUrl: 'https://flagcdn.com/w40/eh.png', isEnabled: true, isDefault: false },
  { name: 'Yemen', codeAlpha2: 'YE', codeAlpha3: 'YEM', numericCode: '887', currencyCode: 'YER', flagImageUrl: 'https://flagcdn.com/w40/ye.png', isEnabled: true, isDefault: false },
  { name: 'Zambia', codeAlpha2: 'ZM', codeAlpha3: 'ZMB', numericCode: '894', currencyCode: 'ZMW', flagImageUrl: 'https://flagcdn.com/w40/zm.png', isEnabled: true, isDefault: false },
  { name: 'Zimbabwe', codeAlpha2: 'ZW', codeAlpha3: 'ZWE', numericCode: '716', currencyCode: 'ZWL', flagImageUrl: 'https://flagcdn.com/w40/zw.png', isEnabled: true, isDefault: false },
];

export const mockCurrencies: Omit<Currency, 'id'>[] = [
  { name: "United States Dollar", code: "USD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.00 },
  { name: "Euro", code: "EUR", symbol: "€", decimalPlaces: 2, isEnabled: true, isDefault: true, exchangeRate: 0.93 },
  { name: "Afghan Afghani", code: "AFN", symbol: "؋", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 71.50 },
  { name: "Albanian Lek", code: "ALL", symbol: "L", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 93.50 },
  { name: "Algerian Dinar", code: "DZD", symbol: "د.ج", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 134.50 },
  { name: "Angolan Kwanza", code: "AOA", symbol: "Kz", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 830.00 },
  { name: "Argentine Peso", code: "ARS", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 890.00 },
  { name: "Armenian Dram", code: "AMD", symbol: "֏", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 387.00 },
  { name: "Aruban Florin", code: "AWG", symbol: "ƒ", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.80 },
  { name: "Australian Dollar", code: "AUD", symbol: "A$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.51 },
  { name: "Azerbaijani Manat", code: "AZN", symbol: "₼", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.70 },
  { name: "Bahamian Dollar", code: "BSD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.00 },
  { name: "Bahraini Dinar", code: "BHD", symbol: ".د.ب", decimalPlaces: 3, isEnabled: true, isDefault: false, exchangeRate: 0.38 },
  { name: "Bangladeshi Taka", code: "BDT", symbol: "৳", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 117.00 },
  { name: "Barbadian Dollar", code: "BBD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2.00 },
  { name: "Belarusian Ruble", code: "BYN", symbol: "Br", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.25 },
  { name: "Belize Dollar", code: "BZD", symbol: "BZ$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2.00 },
  { name: "Bermudian Dollar", code: "BMD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.00 },
  { name: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu.", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 83.50 },
  { name: "Bolivian Boliviano", code: "BOB", symbol: "Bs.", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 6.91 },
  { name: "Bosnia and Herzegovina Convertible Mark", code: "BAM", symbol: "KM", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.81 },
  { name: "Botswana Pula", code: "BWP", symbol: "P", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 13.75 },
  { name: "Brazilian Real", code: "BRL", symbol: "R$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 5.43 },
  { name: "British Pound Sterling", code: "GBP", symbol: "£", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 0.79 },
  { name: "Brunei Dollar", code: "BND", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.35 },
  { name: "Bulgarian Lev", code: "BGN", symbol: "лв", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.81 },
  { name: "Burundian Franc", code: "BIF", symbol: "FBu", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 2850.00 },
  { name: 'Cabo Verdean Escudo', code: 'CVE', symbol: 'Esc', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 102.50 },
  { name: "Cambodian Riel", code: "KHR", symbol: "៛", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 4100.00 },
  { name: "Canadian Dollar", code: "CAD", symbol: "C$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.37 },
  { name: "Cayman Islands Dollar", code: "KYD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 0.83 },
  { name: "Central African CFA Franc", code: "XAF", symbol: "FCFA", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 610.00 },
  { name: "Chilean Peso", code: "CLP", symbol: "$", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 925.00 },
  { name: "Chinese Yuan", code: "CNY", symbol: "¥", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 7.25 },
  { name: "Colombian Peso", code: "COP", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 4100.00 },
  { name: "Comorian Franc", code: "KMF", symbol: "CF", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 457.00 },
  { name: "Congolese Franc", code: "CDF", symbol: "FC", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2785.00 },
  { name: "Costa Rican Colón", code: "CRC", symbol: "₡", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 520.00 },
  { name: "Cuban Peso", code: "CUP", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 24.00 },
  { name: "Czech Koruna", code: "CZK", symbol: "Kč", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 23.25 },
  { name: "Danish Krone", code: "DKK", symbol: "kr", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 6.95 },
  { name: "Djiboutian Franc", code: "DJF", symbol: "Fdj", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 177.72 },
  { name: "Dominican Peso", code: "DOP", symbol: "RD$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 59.00 },
  { name: "East Caribbean Dollar", code: "XCD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2.70 },
  { name: "Egyptian Pound", code: "EGP", symbol: "E£", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 47.50 },
  { name: "Eritrean Nakfa", code: "ERN", symbol: "Nfk", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 15.00 },
  { name: "Eswatini Lilangeni", code: "SZL", symbol: "L", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 18.00 },
  { name: "Ethiopian Birr", code: "ETB", symbol: "Br", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 57.00 },
  { name: "Falkland Islands Pound", code: "FKP", symbol: "£", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 0.79 },
  { name: "Fijian Dollar", code: "FJD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2.25 },
  { name: "Gambian Dalasi", code: "GMD", symbol: "D", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 68.00 },
  { name: "Georgian Lari", code: "GEL", symbol: "₾", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2.80 },
  { name: "Ghanaian Cedi", code: "GHS", symbol: "₵", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 14.80 },
  { name: "Gibraltar Pound", code: "GIP", symbol: "£", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 0.79 },
  { name: "Guatemalan Quetzal", code: "GTQ", symbol: "Q", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 7.78 },
  { name: "Guinean Franc", code: "GNF", symbol: "FG", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 8600.00 },
  { name: "Guyanese Dollar", code: "GYD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 209.00 },
  { name: "Haitian Gourde", code: "HTG", symbol: "G", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 132.00 },
  { name: "Honduran Lempira", code: "HNL", symbol: "L", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 24.60 },
  { name: "Hong Kong Dollar", code: "HKD", symbol: "HK$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 7.81 },
  { name: "Hungarian Forint", code: "HUF", symbol: "Ft", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 365.00 },
  { name: "Icelandic Króna", code: "ISK", symbol: "kr", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 138.00 },
  { name: "Indian Rupee", code: "INR", symbol: "₹", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 83.56 },
  { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 16200.00 },
  { name: "Iranian Rial", code: "IRR", symbol: "﷼", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 42000.00 },
  { name: "Iraqi Dinar", code: "IQD", symbol: "ع.د", decimalPlaces: 3, isEnabled: true, isDefault: false, exchangeRate: 1310.00 },
  { name: "Israeli New Shekel", code: "ILS", symbol: "₪", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.75 },
  { name: "Jamaican Dollar", code: "JMD", symbol: "J$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 155.00 },
  { name: "Japanese Yen", code: "JPY", symbol: "¥", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 157.0 },
  { name: "Jordanian Dinar", code: "JOD", symbol: "JD", decimalPlaces: 3, isEnabled: true, isDefault: false, exchangeRate: 0.71 },
  { name: "Kazakhstani Tenge", code: "KZT", symbol: "₸", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 445.00 },
  { name: "Kenyan Shilling", code: "KES", symbol: "KSh", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 130.00 },
  { name: "Kuwaiti Dinar", code: "KWD", symbol: "K.D.", decimalPlaces: 3, isEnabled: true, isDefault: false, exchangeRate: 0.31 },
  { name: "Kyrgyzstani Som", code: "KGS", symbol: "с", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 88.00 },
  { name: "Lao Kip", code: "LAK", symbol: "₭", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 21800.00 },
  { name: "Lebanese Pound", code: "LBP", symbol: "L£", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 89500.00 },
  { name: "Lesotho Loti", code: "LSL", symbol: "L", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 18.00 },
  { name: "Liberian Dollar", code: "LRD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 194.00 },
  { name: "Libyan Dinar", code: "LYD", symbol: "LD", decimalPlaces: 3, isEnabled: true, isDefault: false, exchangeRate: 4.85 },
  { name: "Macanese Pataca", code: "MOP", symbol: "MOP$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 8.05 },
  { name: "Macedonian Denar", code: "MKD", symbol: "ден", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 57.50 },
  { name: "Malagasy Ariary", code: "MGA", symbol: "Ar", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 4450.00 },
  { name: "Malawian Kwacha", code: "MWK", symbol: "MK", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1735.00 },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 4.70 },
  { name: "Maldivian Rufiyaa", code: "MVR", symbol: "Rf", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 15.40 },
  { name: "Mauritanian Ouguiya", code: "MRU", symbol: "UM", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 39.70 },
  { name: "Mauritian Rupee", code: "MUR", symbol: "₨", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 46.50 },
  { name: "Mexican Peso", code: "MXN", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 18.38 },
  { name: "Moldovan Leu", code: "MDL", symbol: "L", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 17.75 },
  { name: "Mongolian Tögrög", code: "MNT", symbol: "₮", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3450.00 },
  { name: "Moroccan Dirham", code: "MAD", symbol: "DH", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 9.95 },
  { name: "Mozambican Metical", code: "MZN", symbol: "MT", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 63.50 },
  { name: "Myanmar Kyat", code: "MMK", symbol: "K", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2100.00 },
  { name: "Namibian Dollar", code: "NAD", symbol: "$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 18.00 },
  { name: "Nepalese Rupee", code: "NPR", symbol: "₨", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 133.70 },
  { name: "Netherlands Antillean Guilder", code: "ANG", symbol: "ƒ", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.80 },
  { name: "New Zealand Dollar", code: "NZD", symbol: "NZ$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.63 },
  { name: "Nicaraguan Córdoba", code: "NIO", symbol: "C$", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 36.80 },
  { name: "Nigerian Naira", code: "NGN", symbol: "₦", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1480.00 },
  { name: "Norwegian Krone", code: "NOK", symbol: "kr", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 10.57 },
  { name: "Omani Rial", code: "OMR", symbol: "ر.ع.", decimalPlaces: 3, isEnabled: true, isDefault: false, exchangeRate: 0.38 },
  { name: "Pakistani Rupee", code: "PKR", symbol: "₨", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 278.00 },
  { name: "Panamanian Balboa", code: "PAB", symbol: "B/.", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.00 },
  { name: "Papua New Guinean Kina", code: "PGK", symbol: "K", decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.85 },
  { name: "Paraguayan Guaraní", code: "PYG", symbol: "₲", decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 7500.00 },
  { name: 'Peruvian Sol', code: 'PEN', symbol: 'S/.', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.75 },
  { name: 'Philippine Peso', code: 'PHP', symbol: '₱', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 58.70 },
  { name: 'Polish Złoty', code: 'PLN', symbol: 'zł', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.98 },
  { name: 'Qatari Riyal', code: 'QAR', symbol: 'ر.ق', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.64 },
  { name: 'Romanian Leu', code: 'RON', symbol: 'lei', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 4.65 },
  { name: 'Russian Ruble', code: 'RUB', symbol: '₽', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 83.50 },
  { name: 'Rwandan Franc', code: 'RWF', symbol: 'RF', decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 1300.00 },
  { name: 'Samoan Tālā', code: 'WST', symbol: 'T', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2.75 },
  { name: 'Sao Tome and Principe Dobra', code: 'STN', symbol: 'Db', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 24.50 },
  { name: 'Saudi Riyal', code: 'SAR', symbol: 'ر.س', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.75 },
  { name: 'Serbian Dinar', code: 'RSD', symbol: 'дин.', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 109.00 },
  { name: 'Seychellois Rupee', code: 'SCR', symbol: '₨', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 13.50 },
  { name: 'Sierra Leonean Leone', code: 'SLL', symbol: 'Le', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 22500.00 },
  { name: 'Singapore Dollar', code: 'SGD', symbol: 'S$', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1.35 },
  { name: 'Solomon Islands Dollar', code: 'SBD', symbol: '$', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 8.40 },
  { name: 'Somali Shilling', code: 'SOS', symbol: 'S', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 570.00 },
  { name: 'South African Rand', code: 'ZAR', symbol: 'R', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 18.00 },
  { name: 'South Korean Won', code: 'KRW', symbol: '₩', decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 1383.0 },
  { name: 'South Sudanese Pound', code: 'SSP', symbol: '£', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 1550.00 },
  { name: 'Sri Lankan Rupee', code: 'LKR', symbol: 'Rs', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 300.00 },
  { name: 'Sudanese Pound', code: 'SDG', symbol: 'ج.س.', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 600.00 },
  { name: 'Surinamese Dollar', code: 'SRD', symbol: '$', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 35.00 },
  { name: 'Swedish Krona', code: 'SEK', symbol: 'kr', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 10.45 },
  { name: 'Swiss Franc', code: 'CHF', symbol: 'Fr', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 0.89 },
  { name: 'Syrian Pound', code: 'SYP', symbol: '£', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 13000.00 },
  { name: 'New Taiwan Dollar', code: 'TWD', symbol: 'NT$', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 32.30 },
  { name: 'Tajikistani Somoni', code: 'TJS', symbol: 'SM', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 10.90 },
  { name: 'Tanzanian Shilling', code: 'TZS', symbol: 'TSh', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2600.00 },
  { name: 'Thai Baht', code: 'THB', symbol: '฿', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 36.70 },
  { name: 'Tongan Paʻanga', code: 'TOP', symbol: 'T$', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 2.33 },
  { name: 'Trinidad and Tobago Dollar', code: 'TTD', symbol: 'TT$', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 6.78 },
  { name: 'Tunisian Dinar', code: 'TND', symbol: 'DT', decimalPlaces: 3, isEnabled: true, isDefault: false, exchangeRate: 3.12 },
  { name: 'Turkish Lira', code: 'TRY', symbol: '₺', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 32.83 },
  { name: 'Turkmenistani Manat', code: 'TMT', symbol: 'T', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.50 },
  { name: 'Ugandan Shilling', code: 'UGX', symbol: 'USh', decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 3750.00 },
  { name: 'Ukrainian Hryvnia', code: 'UAH', symbol: '₴', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 40.50 },
  { name: 'United Arab Emirates Dirham', code: 'AED', symbol: 'د.إ', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 3.67 },
  { name: 'Uruguayan Peso', code: 'UYU', symbol: '$U', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 39.00 },
  { name: 'Uzbekistani Som', code: 'UZS', symbol: 'so\'m', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 12650.00 },
  { name: 'Vanuatu Vatu', code: 'VUV', symbol: 'VT', decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 125.00 },
  { name: 'Venezuelan Bolívar', code: 'VES', symbol: 'Bs.', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 36.50 },
  { name: 'Vietnamese Đồng', code: 'VND', symbol: '₫', decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 25450.00 },
  { name: 'West African CFA Franc', code: 'XOF', symbol: 'CFA', decimalPlaces: 0, isEnabled: true, isDefault: false, exchangeRate: 610.00 },
  { name: 'Yemeni Rial', code: 'YER', symbol: '﷼', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 250.00 },
  { name: 'Zambian Kwacha', code: 'ZMW', symbol: 'ZK', decimalPlaces: 2, isEnabled: true, isDefault: false, exchangeRate: 25.50 }
];

const defaultFontBody = "Inter";
const defaultFontHeadline = "Poppins";

const lightThemeColors: ThemeColors = {
  background: "240 5.3% 94.9%",
  foreground: "240 10% 3.9%",
  card: "0 0% 100%",
  cardForeground: "240 10% 3.9%",
  popover: "0 0% 100%",
  popoverForeground: "240 10% 3.9%",
  primary: "270 100% 50%",
  primaryForeground: "0 0% 100%",
  secondary: "240 4.8% 95.9%",
  secondaryForeground: "240 5.9% 10%",
  muted: "240 4.8% 95.9%",
  mutedForeground: "240 3.8% 46.1%",
  accent: "300 100% 50%",
  accentForeground: "0 0% 100%",
  destructive: "0 84.2% 60.2%",
  destructiveForeground: "0 0% 98%",
  border: "240 5.9% 90%",
  input: "240 5.9% 90%",
  ring: "270 100% 50%",
};

const darkThemeColors: ThemeColors = {
  background: "240 10% 3.9%",
  foreground: "0 0% 98%",
  card: "240 3.7% 15.9%",
  cardForeground: "0 0% 98%",
  popover: "240 10% 3.9%",
  popoverForeground: "0 0% 98%",
  primary: "270 100% 60%",
  primaryForeground: "0 0% 100%",
  secondary: "240 3.7% 15.9%",
  secondaryForeground: "0 0% 98%",
  muted: "240 3.7% 15.9%",
  mutedForeground: "240 5% 64.9%",
  accent: "300 100% 60%",
  accentForeground: "0 0% 100%",
  destructive: "0 62.8% 30.6%",
  destructiveForeground: "0 0% 98%",
  border: "240 3.7% 15.9%",
  input: "240 3.7% 15.9%",
  ring: "270 100% 60%",
};

const violetteThemeColors: ThemeColors = {
  background: "260 60% 96%",
  foreground: "270 30% 25%",
  card: "0 0% 100%",
  cardForeground: "270 30% 25%",
  popover: "0 0% 100%",
  popoverForeground: "270 30% 25%",
  primary: "270 80% 55%",
  primaryForeground: "0 0% 100%",
  secondary: "260 40% 90%",
  secondaryForeground: "270 30% 35%",
  muted: "260 40% 92%",
  mutedForeground: "270 25% 55%",
  accent: "290 70% 60%",
  accentForeground: "0 0% 100%",
  destructive: "0 84.2% 60.2%",
  destructiveForeground: "0 0% 98%",
  border: "260 30% 85%",
  input: "260 30% 88%",
  ring: "270 80% 55%",
};

const blueThemeColors: ThemeColors = {
  background: "210 100% 97%",
  foreground: "220 60% 20%",
  card: "0 0% 100%",
  cardForeground: "220 60% 20%",
  popover: "0 0% 100%",
  popoverForeground: "220 60% 20%",
  primary: "220 75% 50%",
  primaryForeground: "0 0% 100%",
  secondary: "210 80% 92%",
  secondaryForeground: "220 50% 30%",
  muted: "210 80% 94%",
  mutedForeground: "220 40% 50%",
  accent: "190 80% 45%",
  accentForeground: "0 0% 100%",
  destructive: "0 84.2% 60.2%",
  destructiveForeground: "0 0% 98%",
  border: "210 50% 85%",
  input: "210 50% 88%",
  ring: "220 75% 50%",
};

export const mockThemes: Omit<Theme, 'id'>[] = [
  { name: 'Light', isDefault: true, colors: lightThemeColors, fontBody: defaultFontBody, fontHeadline: defaultFontHeadline },
  { name: 'Dark', colors: darkThemeColors, fontBody: defaultFontBody, fontHeadline: defaultFontHeadline, isDefault: false },
  { name: 'Violette', colors: violetteThemeColors, fontBody: "'Caveat', cursive", fontHeadline: "'Pacifico', cursive", isDefault: false },
  { name: 'Blue', colors: blueThemeColors, fontBody: "'Roboto Slab', serif", fontHeadline: "'Lobster', cursive", isDefault: false },
];

export const mockReceiptSettings: Omit<ReceiptSetting, 'id' | 'key'> = {
  logoUrl: 'https://placehold.co/150x50.png?text=POSIFY',
  footerText: 'Thank you for your business!\\nVisit us at posify.example.com',
  companyName: 'POSIFY Inc.',
  companyAddress: '123 Market Street, Business City, 12345',
  companyPhone: '(555) 123-4567',
  receiptWidth: 'auto',
  receiptMargin: 'small',
  showCompanyName: true,
  showCompanyAddress: true,
  showCompanyPhone: true,
  showClientInfo: true,
  showItemBarcodes: false,
  showDiscountSummary: true,
  showPromotionsApplied: true,
  showPaymentMethodsDetails: true,
};

const oneProduct = mockProducts[0];
const anotherProduct = mockProducts[1];

export const mockPreviewTransaction: SaleTransaction = {
    id: 'PREVIEW-TRANS-001',
    date: new Date().toISOString(),
    items: [
        { ...oneProduct, id: 'MOCK-PROD-PREV-001', productId: 'MOCK-PROD-PREV-001', quantity: 2 },
        { ...anotherProduct, id: 'MOCK-PROD-PREV-002', productId: 'MOCK-PROD-PREV-002', quantity: 1 },
    ] as any, // Cast to any to satisfy TS, while providing data for schema
    subtotal: (oneProduct.price * 2) + anotherProduct.price,
    totalItemDiscountAmount: 0, 
    promotionalDiscountAmount: 5.00, 
    taxAmount: (((oneProduct.price * 2) + anotherProduct.price) - 5.00) * 0.10, 
    totalAmount: ((((oneProduct.price * 2) + anotherProduct.price) - 5.00) * 1.10),
    appliedPayments: [{ methodId: 'pm_cash', methodName: 'Cash', amount: ((((oneProduct.price * 2) + anotherProduct.price) -5.00) * 1.10) }],
    clientId: `MOCK-CLIENT-${mockClients[0].email.split('@')[0]}`,
    clientName: mockClients[0].name,
    appliedTaxes: [{ taxId: 'mock-tax-1', name: 'Sales Tax', rate: 0.10, amount: ((((oneProduct.price * 2) + anotherProduct.price) -5.00) * 0.10) }],
    appliedPromotions: [{ promotionId: 'promo-1', name: '$5 Off Preview', discountType: 'fixedAmount', discountValue: 5, amountDeducted: 5.00 }],
    currencyCode: "USD",
    currencySymbol: "$",
    currencyDecimalPlaces: 2,
    baseCurrencyCode: "USD",
    totalInBaseCurrency: ((((oneProduct.price * 2) + anotherProduct.price) - 5.00) * 1.10),
    exchangeRate: 1,
    dispatchStatus: 'Pending',
};

const generateMockSales = (count: number): Omit<SaleTransaction, 'id'>[] => {
  const sales: Omit<SaleTransaction, 'id'>[] = [];
  const today = new Date();
  for (let i = 0; i < count; i++) {
    const itemsCount = Math.floor(Math.random() * 3) + 1;
    const currentSaleItems: CartItem[] = [];
    for (let j = 0; j < itemsCount; j++) {
      const mockProductIndex = Math.floor(Math.random() * mockProducts.length);
      
      const productSeed = mockProducts[mockProductIndex];
      const cartProduct: any = { // Use 'any' to add both id and productId
        ...productSeed,
        id: `MOCK-PROD-${mockProductIndex + 1}`,
        productId: `MOCK-PROD-${mockProductIndex + 1}` 
      };
      currentSaleItems.push({ ...cartProduct, quantity: Math.floor(Math.random() * 2) + 1 });
    }

    const subtotal = currentSaleItems.reduce((sum, item) => sum + item.price * item.quantity, 0);

    const appliedTaxesForSale: AppliedTaxEntry[] = [];
    let totalTaxAmount = 0;

    const numberOfTaxesToApply = Math.random() > 0.3 ? (Math.random() > 0.6 ? 1 : 0) : (Math.random() > 0.5 ? 2: 1) ;
    const shuffledTaxes = [...mockTaxes].sort(() => 0.5 - Math.random());

    for(let k=0; k < numberOfTaxesToApply && k < shuffledTaxes.length; k++) {
        const tax = shuffledTaxes[k];
        const taxAmountForThis = subtotal * tax.rate;
        const taxId = `MOCK-TAX-${tax.name.replace(/\s+/g, '-')}`;
        appliedTaxesForSale.push({
            taxId: taxId,
            name: tax.name,
            rate: tax.rate,
            amount: parseFloat(taxAmountForThis.toFixed(2))
        });
        totalTaxAmount += taxAmountForThis;
    }

    const totalAmount = subtotal + totalTaxAmount;
    const saleDate = new Date(today);
    saleDate.setDate(today.getDate() - Math.floor(Math.random() * 30));

    const mockEnabledPaymentMethods = mockPaymentMethods.filter(pm => pm.isEnabled);
    const chosenPaymentMethod = mockEnabledPaymentMethods[Math.floor(Math.random() * mockEnabledPaymentMethods.length)];

    const appliedPayments: AppliedPayment[] = [{
        methodId: (chosenPaymentMethod.name as any).en.toLowerCase().replace(/\s+/g, '-'), 
        methodName: (chosenPaymentMethod.name as any).en,
        amount: parseFloat(totalAmount.toFixed(2))
    }];


    const transaction: Omit<SaleTransaction, 'id'> = {
      date: saleDate.toISOString(),
      items: currentSaleItems,
      subtotal: parseFloat(subtotal.toFixed(2)),
      totalItemDiscountAmount: 0, 
      overallDiscountAmountApplied: 0, 
      promotionalDiscountAmount: 0, 
      taxAmount: parseFloat(totalTaxAmount.toFixed(2)),
      totalAmount: parseFloat(totalAmount.toFixed(2)),
      appliedPayments: appliedPayments,
      appliedTaxes: appliedTaxesForSale,
      currencyCode: 'USD',
      currencySymbol: '$',
      currencyDecimalPlaces: 2,
      baseCurrencyCode: 'USD',
      totalInBaseCurrency: parseFloat(totalAmount.toFixed(2)),
      exchangeRate: 1,
      dispatchStatus: 'Pending',
    };

    if (mockClients.length > 0 && Math.random() > 0.5) {
      const randomClient = mockClients[Math.floor(Math.random() * mockClients.length)];
      transaction.clientName = randomClient.name;
      transaction.clientId = `MOCK-CLIENT-${randomClient.email.split('@')[0]}`; 
    }

    sales.push(transaction);
  }
  return sales.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
};

export const mockSalesTransactions: Omit<SaleTransaction, 'id'>[] = generateMockSales(25);

export const mockPromotions: Omit<Promotion, 'id'>[] = [
  {
    name: '10% Off Summer Sale (Drinkware)',
    description: 'Get 10% off on all Drinkware items.',
    discountType: 'percentage',
    discountValue: 10,
    startDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 23).toISOString(),
    conditions: [
      { type: 'productCategories', values: ['Drinkware'], operator: 'in' }
    ],
    isActive: true,
    applicationMethod: 'cart',
  },
  {
    name: '$5 Off Electronics over $50',
    description: 'Spend $50 on Electronics and get $5 off.',
    discountType: 'fixedAmount',
    discountValue: 5,
    startDate: new Date().toISOString(),
    conditions: [
      { type: 'minSellAmount', value: 50, operator: 'gte' },
      { type: 'productCategories', values: ['Electronics'], operator: 'in'}
    ],
    isActive: true,
    applicationMethod: 'cart',
  },
  {
    name: 'Buy 2 Personal Care, Get 50% off cheapest',
    description: 'Buy any 2 items from Personal Care and get 50% off the lowest priced one.',
    discountType: 'percentage',
    discountValue: 50,
    startDate: new Date().toISOString(),
    conditions: [
        { type: 'itemQuantity', value: 2 },
        { type: 'productCategories', values: ['Personal Care'], operator: 'in' },
    ],
    isActive: true,
    applicationMethod: 'lowestPriceItem',
  },
  {
    name: 'VIP Client Special - Tote Bags',
    description: 'VIPs get 15% off Organic Cotton Tote Bags.',
    discountType: 'percentage',
    discountValue: 15,
    startDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 50).toISOString(),
    conditions: [
      { type: 'productIds', values: ['1000000002'], operator: 'in' }, 
      { type: 'clientIds', values: [`MOCK-CLIENT-alice`], operator: 'in' } 
    ],
    isActive: true,
    applicationMethod: 'cart',
  },
  {
    name: 'Pay by Credit Card & Save 5%',
    description: 'Get 5% off your entire purchase when paying with Credit Card.',
    discountType: 'percentage',
    discountValue: 5,
    startDate: new Date().toISOString(),
    conditions: [
        { type: 'paymentMethods', values: ['credit-card'], operator: 'in' } 
    ],
    isActive: true,
    applicationMethod: 'cart',
  },
  {
    name: 'Expired Test Promo',
    description: 'This promotion should not be active.',
    discountType: 'percentage',
    discountValue: 20,
    startDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    endDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    conditions: [],
    isActive: false,
    applicationMethod: 'cart', 
  },
];

export const mockSuppliers: Omit<Supplier, 'id'>[] = [
  { name: 'Green Supplies Co.', contactPerson: 'John Green', email: 'contact@greensupplies.co', phone: '555-0101', address: '100 Eco Park, Greentown', isEnabled: true },
  { name: 'Eco Textiles Inc.', contactPerson: 'Jane Fabric', email: 'sales@ecotextiles.com', phone: '555-0102', address: '200 Organic Way, Fiberburg', isEnabled: true },
  { name: 'Natural Dental Care', contactPerson: 'Dr. Mint', email: 'orders@naturaldental.com', phone: '555-0103', address: '300 Fresh Ave, Smileville', isEnabled: true },
  { name: 'SunPower Tech', contactPerson: 'Leo Solar', email: 'info@sunpower.tech', phone: '555-0104', address: '400 Watt St, Electri-city', isEnabled: false },
  { name: 'The Coffee Roasters', contactPerson: 'Barry Bean', email: 'barry@thecoffeeroasters.com', phone: '555-0105', address: '500 Aroma Blvd, Javaville', isEnabled: true },
];

    