// src/i18n-config.ts
// THIS FILE IS AUTO-GENERATED BY THE LANGUAGES MANAGER API.
// DO NOT EDIT MANUALLY.
// A SERVER RESTART IS REQUIRED FOR CHANGES TO TAKE EFFECT.

export const locales = ["en","es"];
export const defaultLocale = 'es';
